Bump aarch32 to jdk8u192-b12-aarch32-181022.
Upstream changes:
  - S6730115: Fastdebug VM crashes with "ExceptionMark destructor expects no pending exceptions" error
  - S8008321: compile.cpp verify_graph_edges uses bool as int
  - S8026331: hs_err improvement: Print if we have seen any OutOfMemoryErrors or StackOverflowErrors
  - S8026335: hs_err improvement: Print exact compressed oops mode and the heap base value.
  - S8035074: hs_err improvement: Add time zone information in the hs_err file
  - S8038636: speculative traps break when classes are redefined
  - S8041623: Solaris Studio 12.4 C++ 5.13, CHECK_UNHANDLED_OOPS use of class oop's copy constructor definitions causing error level diagnostic.
  - S8048128: Fix for Solaris Studio C++ 5.13, CHECK_UNHANDLED_OOPS breaks PPC build.
  - S8055008: Clean up code that saves the previous versions of redefined classes
  - S8057570: RedefineClasses() tests fail assert(((Metadata*)obj)->is_valid()) failed: obj is valid
  - S8069124: runtime/NMT/MallocSiteHashOverflow.java failing in nightlies
  - S8077420: Build failure with SS12u4
  - S8078628: linux-zero does not build without precompiled header
  - S8081202: Hotspot compile warning: "Invalid suffix on literal; C++11 requires a space between literal and identifier"
  - S8081323: ConstantPool::_resolved_references is missing in heap dump
  - S8114823: G1 doesn't honor request to disable class unloading
  - S8134157: adlc fails to compile with SS12u4
  - S8138692: libjsig compilation is missing EXTRA_CFLAGS on macosx
  - S8146115: Improve docker container detection and resource configuration usage
  - S8148175: C1: G1 barriers don't preserve FP registers
  - S8150426: Wrong cast in metadata_at_put
  - S8150688: Fix os_windows siglabel
  - S8153194: PreserveFPRegistersTest.java runs out of memory in the nightlies
  - S8156137: SIGSEGV in ReceiverTypeData::clean_weak_klass_links
  - S8158012: Use SW prefetch instructions instead of BIS for allocation prefetches on SPARC Core C4
  - S8160748: Inconsistent types for ideal_reg
  - S8162540: Crash in C2 escape analysis with assert: "node should be registered"
  - S8164480: Crash with assert(handler_address == SharedRuntime::compute_compiled_exc_handler(..) failed: Must be the same
  - S8165489: Missing G1 barrier in Unsafe_GetObjectVolatile
  - S8169201: Montgomery multiply intrinsic should use correct name
  - S8173013: JVMTI tagged object access needs G1 pre-barrier
  - S8185723: Zero: segfaults on Power PC 32-bit
  - S8186461: Zero's atomic_copy64() should use SPE instructions on linux-powerpcspe
  - S8187045: [linux] Not all libraries in the VM are linked with -z,noexecstack
  - S8187577: JVM crash during gc doing concurrent marking
  - S8188223: IfNode::range_check_trap_proj() should handler dying subgraph with single if proj
  - S8189170: Add option to disable stack overflow checking in primordial thread for use with JNI_CreateJavaJVM
  - S8189851: [TESTBUG] runtime/RedefineTests/RedefineInterfaceCall.java fails
  - S8194642: Improve OOM error reporting for JDK8
  - S8194739: Zero port of 8174962: Better interface invocations
  - S8196880: VS2017 Addition of Global Delete Operator with Size Parameter Conflicts with Arena's Chunk Provided One
  - S8196884: VS2017 Multiple Type Cast Conversion Compilation Errors
  - S8197864: VS2017 (C4334) Result of 32-bit Shift Implicitly Converted to 64 bits
  - S8197868: VS2017 (C2065) 'timezone': Undeclared Identifier in share/runtime/os.cpp
  - S8198304: VS2017 (C4838, C4312) Various conversion issues with gtest tests
  - S8198794: Hotspot crash on Cassandra 3.11.1 startup with libnuma 2.0.3
  - S8199406: Performance drop with Java JDK 1.8.0_162-b32
  - S8201509: Zero: S390 31bit atomic_copy64 inline assembler is wrong
  - S8202600: [Zero] Undefined behaviour in src/os_cpu/linux_zero/vm/os_linux_zero.cpp
  - S8203349: 8u hotspot should recognise later Windows compilers
  - S8204053: libsaproc.so not linked with -z,noexecstack
  - S8204872: [8u] VS2017: more instances of "error C3680: cannot concatenate user-defined string literals with mismatched literal suffix identifiers"
  - S8205104: EXTRA_LDFLAGS not consistently being used
  - S8205440: [8u] DWORD64 required for later Windows compilers
  - S8205677: [8u] casts and type change for 8u to enable later Windows compilers
  - S8206406: StubCodeDesc constructor publishes partially-constructed objects on StubCodeDesc::_list
  - S8206425: .gnu_debuglink sections added unconditionally when no debuginfo is stripped
  - S8206454: [8u] os::current_stack_pointer() fails to compile on later Windows compilers (warning C4172: returning address of local variable)
  - S8207402: Stray *.debuginfo files when not stripping debug info

ChangeLog:

2019-02-03  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	Bump aarch32 to jdk8u192-b12-aarch32-181022.
	* patches/hotspot/aarch32/8008321-pr3599.patch,
	* patches/hotspot/aarch32/8165489-pr3589.patch,
	* patches/hotspot/aarch32/8185723-pr3553.patch,
	* patches/hotspot/aarch32/8186461-pr3557.patch,
	* patches/hotspot/aarch32/8201509-pr3579.patch,
	* patches/hotspot/aarch32/8206406-pr3610-rh1597825.patch,
	* patches/hotspot/aarch32/pr3539-rh1548475.patch:
	Remove patches now upstream.
	* Makefile.am:
	(ICEDTEA_PATCHES): Remove AArch32-only patches which
	are now included in the updated tarball.
	* NEWS: Updated.
	* hotspot.map.in: Bump aarch32 to
	jdk8u192-b12-aarch32-181022.
	* patches/hotspot/aarch32/8141491-pr3159-g592292.patch,
	* patches/hotspot/aarch32/8143245-pr3548.patch,
	* patches/hotspot/aarch32/8158260-pr2991-rh1341258.patch,
	* patches/hotspot/aarch32/8197429-pr3546-rh1536622.patch,
	* patches/hotspot/aarch32/pr1368.patch,
	* patches/hotspot/aarch32/pr3593.patch,
	* patches/hotspot/aarch32/pr3607.patch,
	* patches/hotspot/aarch32/werror.patch:
	Replace pre-8u192 versions with symlinks to Shenandoah
	versions.