Bump to icedtea-3.11.0pre02.
Upstream changes:
  - PR3683: Addition of 8189170 in 8u192 breaks 8197429 backport
  - S6260348: GTK+ L&F JTextComponent not respecting desktop caret blink rate
  - S6730115: Fastdebug VM crashes with "ExceptionMark destructor expects no pending exceptions" error
  - S8008321: compile.cpp verify_graph_edges uses bool as int
  - S8022177: Windows/MSYS builds broken
  - S8026331: hs_err improvement: Print if we have seen any OutOfMemoryErrors or StackOverflowErrors
  - S8026335: hs_err improvement: Print exact compressed oops mode and the heap base value.
  - S8027584: Disable ccache by default
  - S8031668: TOOLCHAIN_FIND_COMPILER unexpectedly resolves symbolic links
  - S8031759: Improved tool overriding in configure
  - S8033292: only warn, not fail, on unknown variables in configure
  - S8034199: Add 'reconfigure' target for re-creating a configuration
  - S8034788: Rewrite toolchain.m4 to support multiple toolchains per platform.
  - S8035074: hs_err improvement: Add time zone information in the hs_err file
  - S8035495: Improvements in autoconf integration
  - S8035725: Must keep microsoft VS_PATH on PATH after toolchain detection
  - S8035730: Configure fails in cygwin if current dir is in /home/user
  - S8035751: Clean up Visual Studio detection logic
  - S8035825: Warn instead of fail when calling the configure wrapper directly
  - S8036003: Add --with-native-debug-symbols=[none|internal|external|zipped]
  - S8038340: Cleanup and fix sysroot and devkit handling on Linux and Solaris
  - S8038636: speculative traps break when classes are redefined
  - S8039030: 9-dev windows-i586 build failed with mktemp: command not found
  - S8041623: Solaris Studio 12.4 C++ 5.13, CHECK_UNHANDLED_OOPS use of class oop's copy constructor definitions causing error level diagnostic.
  - S8042707: Source changes needed to build JDK 9 with Visual Studio 2013 (VS2013)
  - S8048128: Fix for Solaris Studio C++ 5.13, CHECK_UNHANDLED_OOPS breaks PPC build.
  - S8051972: sun/security/pkcs11/ec/ReadCertificates.java fails intermittently
  - S8055008: Clean up code that saves the previous versions of redefined classes
  - S8057538: Build the freetype library during configure on Windows
  - S8057570: RedefineClasses() tests fail assert(((Metadata*)obj)->is_valid()) failed: obj is valid
  - S8061305: Javadoc crashes when method name ends with "Property"
  - S8067239: [TESTBUG] javax/xml/bind/marshal/8036981/Test.java failed
  - S8069124: runtime/NMT/MallocSiteHashOverflow.java failing in nightlies
  - S8074373: NMT is not enabled if NMT option is specified after class path specifiers
  - S8074462: Handshake messages can be strictly ordered
  - S8074859, PR1937: Re-apply warnings as error switch removed by 8034788 in 8u192
  - S8075942: ArrayIndexOutOfBoundsException in sun.java2d.pisces.Dasher.goTo
  - S8076117: EndEntityChecker should not process custom extensions after PKIX validation
  - S8077420: Build failure with SS12u4
  - S8078437: Enable use of devkits for Windows
  - S8078628: linux-zero does not build without precompiled header
  - S8079788: Fix broken CL version detection in configure for some Visual Studio configurations
  - S8081202: Hotspot compile warning: "Invalid suffix on literal; C++11 requires a space between literal and identifier"
  - S8081323: ConstantPool::_resolved_references is missing in heap dump
  - S8114823: G1 doesn't honor request to disable class unloading
  - S8134157: adlc fails to compile with SS12u4
  - S8138692: libjsig compilation is missing EXTRA_CFLAGS on macosx
  - S8140470: javax/xml/crypto/dsig/SecurityManager/XMLDSigWithSecMgr.java failed with AccessControlException
  - S8145188, PR2945: Re-apply --with-java-debug-symbols option removed by 8034788 in 8u192
  - S8146115: Improve docker container detection and resource configuration usage
  - S8148175: C1: G1 barriers don't preserve FP registers
  - S8148351: Only display resolved symlink for compiler, do not change path
  - S8150426: Wrong cast in metadata_at_put
  - S8150688: Fix os_windows siglabel
  - S8150954: Taking screenshots on x11 composite desktop produce wrong result
  - S8152974: AWT hang occurrs when sequenced events arrive out of sequence
  - S8153194: PreserveFPRegistersTest.java runs out of memory in the nightlies
  - S8156137: SIGSEGV in ReceiverTypeData::clean_weak_klass_links
  - S8156824: com.sun.jndi.ldap.pool.PoolCleaner should clear its context class loader
  - S8157898: SupportedDSAParamGen.java failed with timeout
  - S8158012: Use SW prefetch instructions instead of BIS for allocation prefetches on SPARC Core C4
  - S8160748: Inconsistent types for ideal_reg
  - S8160748, PR3682: [AArch64] Inconsistent types for ideal_reg
  - S8162362: Introduce system property to control enabled ciphersuites
  - S8162540: Crash in C2 escape analysis with assert: "node should be registered"
  - S8164480: Crash with assert(handler_address == SharedRuntime::compute_compiled_exc_handler(..) failed: Must be the same
  - S8165463: Native implementation of sunmscapi should use operator new (nothrow) for allocations
  - S8165489: Missing G1 barrier in Unsafe_GetObjectVolatile
  - S8168628: (fc) SIGBUS when extending file size to map it
  - S8169201: Montgomery multiply intrinsic should use correct name
  - S8171452: (ch) linux io_util_md: Operation not supported exception after 8168628
  - S8173013: JVMTI tagged object access needs G1 pre-barrier
  - S8176033: New cygwin grep does not match \r as newline
  - S8176183: sun/security/mscapi/SignedObjectChain.java fails on Windows
  - S8176192: Incorrect usage of Iterator in Java 8 In com.sun.jndi.ldap.EventSupport.removeNamingListener
  - S8177758: Regression in java.awt.FileDialog
  - S8178370: [TEST_BUG] java/security/Signature/SignatureLength.java fails
  - S8179079: Incremental HotSpot builds broken on Windows
  - S8179675: Build with error on windows with new Cygwin grep
  - S8185723: Zero: segfaults on Power PC 32-bit
  - S8185855: Debug exception stacks should be clearer
  - S8186171: HashMap: Entry.setValue may not work after Iterator.remove() called for previous entries
  - S8186461: Zero's atomic_copy64() should use SPE instructions on linux-powerpcspe
  - S8186646: Nashorn: "duplicate code" assertion when binding a vararg function that just passes arguments along
  - S8187045: [linux] Not all libraries in the VM are linked with -z,noexecstack
  - S8187577: JVM crash during gc doing concurrent marking
  - S8187635: On Windows Swing changes keyboard layout on a window activation
  - S8187803: JDK part of JavaFX-Swing dialogs appearing behind main stage
  - S8188030: AWT java apps fail to start when some minimal fonts are present
  - S8188083: NullPointerExcpn-java.awt.image.FilteredImageSource.startProduction JDK-8079607
  - S8188223: IfNode::range_check_trap_proj() should handler dying subgraph with single if proj
  - S8189170: Add option to disable stack overflow checking in primordial thread for use with JNI_CreateJavaJVM
  - S8189170, PR3682: [AArch64] Add option to disable stack overflow checking in primordial thread for use with JNI_CreateJavaJVM
  - S8189760: sun/security/ssl/CertPathRestrictions/TLSRestrictions.java failed with unexpected Exception intermittently
  - S8189851: [TESTBUG] runtime/RedefineTests/RedefineInterfaceCall.java fails
  - S8193171: keytool -list displays "JKS" for a PKCS12 keystore
  - S8193758: Update copyright headers of files in src tree that are missing Classpath exception
  - S8193892: Impact of noncloneable MessageDigest implementation
  - S8194412: Adding 256 units of IsoFields.QUARTER_YEARS broken
  - S8194642: Improve OOM error reporting for JDK8
  - S8194739: Zero port of 8174962: Better interface invocations
  - S8195095: Images are not scaled correctly in JEditorPane
  - S8195738: scroll poistion in ScrollPane is reset after calling validate()
  - S8195837: (tz) Upgrade time-zone data to tzdata2018c
  - S8196108: Add build support for VS 2015/2017
  - S8196491: Newlines in JAXB string values of SOAP-requests are escaped to "&#xa;"
  - S8196516: libfontmanager must be built with LDFLAGS allowing unresolved symbols
  - S8196854: TestFlushableGZIPOutputStream failing with IndexOutOfBoundsException
  - S8196880: VS2017 Addition of Global Delete Operator with Size Parameter Conflicts with Arena's Chunk Provided One
  - S8196884: VS2017 Multiple Type Cast Conversion Compilation Errors
  - S8196952: Bad primeCertainty value setting in DSAParameterGenerator
  - S8197518: Kerberos krb5 authentication: AuthList's put method leads to performance issue
  - S8197864: VS2017 (C4334) Result of 32-bit Shift Implicitly Converted to 64 bits
  - S8197868: VS2017 (C2065) 'timezone': Undeclared Identifier in share/runtime/os.cpp
  - S8197943: Unable to use JDWP API in JDK 8 to debug JDK 9 VM
  - S8198304: VS2017 (C4838, C4312) Various conversion issues with gtest tests
  - S8198605: Touch keyboard is shown for a non-focusable text component
  - S8198606: Touch keyboard does not hide, when a text component looses focus
  - S8198794: Hotspot crash on Cassandra 3.11.1 startup with libnuma 2.0.3
  - S8198898: Compilation errors in jdk.crypto.mscapi with VS 2017
  - S8199406: Performance drop with Java JDK 1.8.0_162-b32
  - S8199748: Touch keyboard is not shown, if text component gets focus from other text component
  - S8200353: Shift or Capslock not working in Textfield after accented keystrokes
  - S8200359: (tz) Upgrade time-zone data to tzdata2018d
  - S8201240: Improve releasing native resources of BufImgSurfaceData.ICMColorData
  - S8201369: Inet4AddressImpl_getLocalHostName reverse lookup on Solaris only
  - S8201433: Fix potential crash in BufImg_SetupICM
  - S8201495: [Zero] Reduce limits of max heap size for boot JDK on s390
  - S8201509: Zero: S390 31bit atomic_copy64 inline assembler is wrong
  - S8202478: Backout JDK-8152974
  - S8202600: [Zero] Undefined behaviour in src/os_cpu/linux_zero/vm/os_linux_zero.cpp
  - S8202696: Remove exclusion range for phonetic chars in windows fontconfig.properties
  - S8202996: Remove debug print statements from RMI fix
  - S8203182: Release session if initialization of SunPKCS11 Signature fails
  - S8203233: (tz) Upgrade time-zone data to tzdata2018e
  - S8203349: 8u hotspot should recognise later Windows compilers
  - S8203368: ObjectInputStream filterCheck method throws NullPointerException
  - S8203499: Uninitialised memory in WinAccessBridge.cpp
  - S8203790: MSVCP dependency introduced in awt.dll
  - S8203845: backport of JDK-8034788 inadvertently rolled back JDK-8187045 changes to toolchain.m4
  - S8204053: libsaproc.so not linked with -z,noexecstack
  - S8204872: [8u] VS2017: more instances of "error C3680: cannot concatenate user-defined string literals with mismatched literal suffix identifiers"
  - S8205104: EXTRA_LDFLAGS not consistently being used
  - S8205440: [8u] DWORD64 required for later Windows compilers
  - S8205677: [8u] casts and type change for 8u to enable later Windows compilers
  - S8206406: StubCodeDesc constructor publishes partially-constructed objects on StubCodeDesc::_list
  - S8206425: .gnu_debuglink sections added unconditionally when no debuginfo is stripped
  - S8206454: [8u] os::current_stack_pointer() fails to compile on later Windows compilers (warning C4172: returning address of local variable)
  - S8206914: add jdk8u-dev test failures to ProblemList.txt
  - S8207402: Stray *.debuginfo files when not stripping debug info
  - S8207853: Need to regenerate configure in jdk8u-dev
  - S8209002: 8u192 installed exe and dll files have wrong file version
  - S8209414, PR3682: AArch64: method handle invocation does not respect JVMTI interp_only mode
  - S8210423: Backport of 8034788 breaks GCC version detection
  - S8210658: Remove and retag jdk8u192-b10 tag in source repository
  - S8210951: Test sun/security/ssl/SSLContextImpl/CustomizedCipherSuites.java fails

ChangeLog:

2019-01-23  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	Bump to icedtea-3.11.0pre02.
	* Makefile.am,
	(CORBA_CHANGESET): Update to icedtea-3.11.0pre02 tag.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(NASHORN_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	(NASHORN_SHA256SUM): Likewise.
	(ICEDTEA_CONFIGURE): Add --with-native-debug-symbols,
	set to internal when building with native
	debuginfo and none otherwise.
	(ICEDTEA_ENV): Remove obsolete setting of POST_STRIP_CMD,
	DEBUG_BINARIES and STRIP_POLICY.
	* NEWS: Updated.
	* acinclude.m4,
	(IT_DETERMINE_VERSION): Update JDK_UPDATE_VERSION to 192.
	* configure.ac: Bump to 3.11.0pre02.
	* hotspot.map.in: Update to icedtea-3.11.0pre02 tag.