Bump to icedtea-3.1.0pre01.
Upstream changes:

  - S6869327: Add new C2 flag to keep safepoints in counted loops.
  - S8002116: This JdbReadTwiceTest.sh gets an exit 1
  - S8007890: [TESTBUG] JcmdWithNMTDisabled.java fails when invoked with NMT explicitly turned on
  - S8022865: [TESTBUG] Compressed Oops testing needs to be revised
  - S8029630: Thread id should be displayed as a hex number in error report
  - S8029726: On OS X some dtrace probe names are mismatched with Solaris
  - S8029727: On OS X dtrace probes Call<type>MethodA/Call<type>MethodV are not fired.
  - S8029728: On OS X dtrace probes SetStaticBooleanField are not fired
  - S8036132: Tab characters in test/com/sun/jdi files
  - S8038184: XMLSignature throws StringIndexOutOfBoundsException if ID attribute value is empty String
  - S8038349: Signing XML with DSA throws Exception when key is larger than 1024 bits
  - S8038963: com/sun/jdi tests fail because cygwin's ps sometimes misses processes
  - S8041501: ImageIO reader is not capable of reading JPEGs without JFIF header
  - S8041900: [macosx] Java forces the use of discrete GPU
  - S8044363: Remove special build options for unpack200 executable
  - S8044419: TEST_BUG: com/sun/jdi/JdbReadTwiceTest.sh fails when run under root
  - S8046471: Use OPENJDK_TARGET_CPU_ARCH instead of legacy value for hotspot ARCH
  - S8046611: Build errors with gcc on sparc/fastdebug
  - S8047763: Recognize sparc64 as a sparc platform
  - S8048232: Fix for 8046471 breaks PPC64 build
  - S8052396: Catch exceptions resulting from missing font cmap
  - S8058563: InstanceKlass::_dependencies list isn't cleared from empty nmethodBucket entries
  - S8059661: Test SoftReference and OOM behavior
  - S8061624: [TESTBUG] Some tests cannot be ran under compact profiles and therefore shall be excluded
  - S8062901: Iterators is spelled incorrectly in the Javadoc for Spliterator
  - S8064330: Remove SHA224 from the default support list if SunMSCAPI enabled
  - S8065579: WB method to start G1 concurrent mark cycle should be introduced
  - S8065986: Compiler fails to NullPointerException when calling super with Object<>()
  - S8066974: Compiler doesn't infer method's generic type information in lambda body
  - S8067422: Lambda method names are unnecessarily unstable
  - S8067800: Clarify java.time.chrono.Chronology.isLeapYear for out of range years
  - S8068033: JNI exception pending in jdk/src/share/bin/java.c
  - S8068042: Check jdk/src/share/native/sun/misc/URLClassPath.c for JNI pending
  - S8068162: jvmtiRedefineClasses.cpp: guarantee(false) failed: OLD and/or OBSOLETE method(s) found
  - S8068254: Method reference uses wrong qualifying type
  - S8068761: Test java/nio/channels/ServerSocketChannel/AdaptServerSocket.java failed with SocketTimeoutException
  - S8073735: [TEST_BUG] compiler/loopopts/CountedLoopProblem.java got OOME
  - S8074146: jdb has succeded to read an unreadable file
  - S8074146: [TEST_BUG] jdb has succeded to read an unreadable file
  - S8074696: Remote debugging session hangs for several minutes when calling findBootType
  - S8074935: jdk8 keytool doesn't validate pem files for RFC 1421 correctness, as jdk7 did
  - S8078423: [TESTBUG] javax/print/PrintSEUmlauts/PrintSEUmlauts.java relies on system locale
  - S8080492: [Parfait] Uninitialised variable in jdk/src/java/desktop/windows/native/libawt/
  - S8080650: Enable stubs to use frame pointers correctly
  - S8087120: [GCC5] java.lang.StackOverflowError on Zero JVM initialization on non x86 platforms.
  - S8122944: perfdata used is seen as too high on sparc zone with jdk1.9 and causes a test failure
  - S8129348: Debugger hangs in trace mode with TRACE_SENDS
  - S8129847: Compiling methods generated by Nashorn triggers high memory usage in C2
  - S8129952: Ensure thread consistency
  - S8130212: Thread::current() might access freed memory on Solaris
  - S8130506: javac AssertionError when invoking MethodHandle.invoke with lambda parameter
  - S8130910: hsperfdata file is created in wrong directory and not cleaned up if /tmp/hsperfdata_<username> has wrong permissions
  - S8131129: Attempt to define a duplicate BMH$Species class
  - S8131665: Bad exception message in HandshakeHash.getFinishedHash
  - S8131782: C1 Class.cast optimization breaks when Class is loaded from static final
  - S8132051: Better byte behavior
  - S8132503: [macosx] Chinese full stop symbol cannot be entered with Pinyin IM on OS X
  - S8132890: Text Overlapping on Dot Matrix Printers
  - S8132988: Better printing dialogues
  - S8133207: ParallelProbes.java test fails after changes for JDK-8080115
  - S8133924: NPE may be thrown when xsltc select a non-existing node after JDK-8062518
  - S8134007: Improve string folding
  - S8134297: NPE in GSSNameElement nameType check
  - S8134650: Xsl transformation gives different results in 8u66
  - S8134759: jdb: Incorrect stepping inside finally block
  - S8134828: Scrollbar thumb disappears with Nimbus L&F
  - S8134963: [Newtest] New stress test for changing the coarseness level of G1 remembered set
  - S8136442: Don't tie Certificate signature algorithms to ciphersuites
  - S8137106: EUDC (End User Defined Characters) are not displayed on Windows with Java 8u60+
  - S8138589: Correct limits on unlimited cryptography
  - S8138593: Make DSA more fair
  - S8138745: Implement ExitOnOutOfMemory and CrashOnOutOfMemory in HotSpot
  - S8138764: In some cases the usage of TreeLock can be replaced by other synchronization
  - S8138811: Construction of static protection domains
  - S8138966: Intermittent SEGV running ParallelGC
  - S8139008: Better state table management
  - S8139012: Better font substitutions
  - S8139017: More stable image decoding
  - S8139258: PPC64LE: argument passing problem when passing 15 floats in native call
  - S8139373: [TEST_BUG] java/net/MulticastSocket/MultiDead.java failed with timeout
  - S8139421: PPC64LE: MacroAssembler::bxx64_patchable kill register R12
  - S8139424: SIGSEGV, Problematic frame: # V [libjvm.so+0xd0c0cc] void InstanceKlass::oop_oop_iterate_oop_maps_specialized<true,oopDesc*,MarkAndPushClosure>
  - S8139436: sun.security.mscapi.KeyStore might load incomplete data
  - S8139751: Javac crash with -XDallowStringFolding=false
  - S8139863: [TESTBUG] Need to port tests for JDK-8134903 to 8u-dev
  - S8139985: JNI exception pending in jdk/src/jdk/hprof/agent/share/native/libhprof
  - S8140031: SA: Searching for a value in Threads does not work
  - S8140244: Port fix of JDK-8075773 to AIX and possibly MacOSX
  - S8140249: JVM Crashing During startUp If Flight Recording is enabled
  - S8140268: Generate link to specification license for JavaDoc API documentation
  - S8140344: add support for 3 digit update release numbers
  - S8140483: Atomic*FieldUpdaters final fields should be trusted
  - S8140543: Arrange font actions
  - S8140587: Atomic*FieldUpdaters should use Class.isInstance instead of direct class check
  - S8141213: [Parfait]Potentially blocking function GetArrayLength called in JNI critical region at line 239 of jdk/src/share/native/sun/awt/image/jpeg/jpegdecoder.c in function GET_ARRAYS
  - S8141229: [Parfait] Null pointer dereference in cmsstrcasecmp of cmserr.c
  - S8141260: isReachable crash in windows xp
  - S8141287: Add MD5 to jdk.certpath.disabledAlgorithms - Take 2
  - S8143002: [Parfait] JNI exception pending in fontpath.c:1300
  - S8143167: Better buffering of XML strings
  - S8143185: Cleanup for handling proxies
  - S8143297: Nashorn compilation time reported in nanoseconds
  - S8143397: It looks like InetAddress.isReachable(timeout) works incorrectly
  - S8143855: Bad printf formatting in frame_zero.cpp
  - S8143896: java.lang.Long is implicitly converted to double
  - S8143941: Update splashscreen displays
  - S8143945: Better GCM validation
  - S8143959: Certificates requiring blacklisting
  - S8143963: improve ClassLoader::trace_class_path to accept an additional outputStream* arg
  - S8144020: Remove long as an internal numeric type
  - S8144131: ArrayData.getInt implementations do not convert to int32
  - S8144430: Improve JMX connections
  - S8144483: One long Safepoint pause directly after each GC log rotation
  - S8144487: PhaseIdealLoop::build_and_optimize() must restore major_progress flag if skip_loop_opts is true
  - S8144773: Further reduce use of MD5
  - S8144885: agent/src/os/linux/libproc.h needs to support Linux/SPARC builds
  - S8144935: C2: safepoint is pruned from a non-counted loop
  - S8144937: [TEST_BUG] testlibrary_tests should be excluded for compact1 and compact2 execution
  - S8144955: Wrong changes were pushed with 8143942
  - S8145017: Add support for 3 digit hotspot minor version numbers
  - S8145099: Better error message when SA can't attach to a process
  - S8145442: Add the facility to verify remembered sets for G1
  - S8145466: javac: No line numbers in compilation error
  - S8145539: (coll) AbstractMap.keySet and .values should not be volatile
  - S8145550: Megamorphic invoke should use CompiledFunction variants without any LinkLogic
  - S8145551: Test failed with Crash for Improved font lookups
  - S8145669: apply2call optimized callsite fails after becoming megamorphic
  - S8145722: NullPointerException in javadoc
  - S8145754: PhaseIdealLoop::is_scaled_iv_plus_offset() does not match AddI
  - S8146147: Java linker indexed property getter does not work for computed nashorn string
  - S8146477: [TEST_BUG] ClientJSSEServerJSSE.java failing again
  - S8146494: Better ligature substitution
  - S8146498: Better device table adjustments
  - S8146518: Zero interpreter broken with better byte behaviour
  - S8146566: OpenJDK build can't handle commas in LDFLAGS
  - S8146725: Issues with SignatureAndHashAlgorithm.getSupportedAlgorithms
  - S8146967: [TEST_BUG] javax/security/auth/SubjectDomainCombiner/Optimize.java should use 4-args ProtectionDomain constructor
  - S8146979: Backport of 8046471 breaks ppc64 build in jdk8u because 8072383 was badly backported before
  - S8147087: Race when reusing PerRegionTable bitmaps may result in dropped remembered set entries
  - S8147567: InterpreterRuntime::post_field_access not updated for boolean in JDK-8132051
  - S8147630: Wrong test result pushed to 8u-dev
  - S8147845: Varargs Array functions still leaking longs
  - S8147857: RMIConnector logs attribute names incorrectly
  - S8148353: [linux-sparc] Crash in libawt.so on Linux SPARC
  - S8148446: (tz) Support tzdata2016a
  - S8148475: Missing SA Bytecode updates.
  - S8148487: PPC64: Better byte behavior
  - S8148522: Backout JDK-8138811 from 2016 Apr CPU repo
  - S8149170: Better byte behavior for native arguments
  - S8149367: PolicyQualifierInfo/index_Ctor JCk test fails with IOE: Invalid encoding for PolicyQualifierInfo
  - S8150012: Better byte behavior for reflection
  - S8150790: 8u75 L10n resource file translation update
  - S8150791: 8u76 L10n resource file translation update

ChangeLog:

2016-05-16  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	Bump to icedtea-3.1.0pre01.
	* Makefile.am:
	(JDK_UPDATE_VERSION): Bump to 92.
	(BUILD_VERSION): Set to b14.
	(CORBA_CHANGESET): Update to icedtea-3.1.0pre01 tag.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(NASHORN_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	(NASHORN_SHA256SUM): Likewise.
	* NEWS: Add 3.1.0 section and include u92
	changes.
	* configure.ac: Bump to 3.1.0pre01.
	* hotspot.map.in: Update to icedtea-3.1.0pre01 tag.